server:
  port: 9093
spring:
  application:
    name: sport-user-comsumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

#fuzaijunheng