server:
  port: 9094
spring:
  application:
    name: sport-column-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true


