server:
  port: 8082
spring:
  application:
    name: sport-friend-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_invitation
    username: root
    password: ok
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
